services:
  postgres:
    image: postgres
    container_name: postgres-sql
    environment:
     - POSTGRES_DB=demo_db
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=username
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    networks:
      - spring-boot-network
  spring-boot-app:
    container_name: spring-demo
    image: spring/demo
    ports:
      - "8080:8080"
    networks:
      - spring-boot-network
    depends_on:
      - postgres
volumes:
  postgres:
networks:
  spring-boot-network:
    driver: bridge
